In [16]:
import tensorflow as tf
import numpy as np


In [17]:
tensor_x = tf.constant([9,6,3,0],shape=(2,2),dtype=tf.int64)
tensor_y = tf.constant([3,6,4,1],shape=(2,2),dtype=tf.int64)
print(tensor_x)
print(tensor_y)

tf.Tensor(
[[9 6]
 [3 0]], shape=(2, 2), dtype=int64)
tf.Tensor(
[[3 6]
 [4 1]], shape=(2, 2), dtype=int64)


In [18]:
print('Using multiply: ',tf.multiply(tensor_x,tensor_y))

Using multiply:  tf.Tensor(
[[27 36]
 [12  0]], shape=(2, 2), dtype=int64)


In [19]:
print('Using matmul: ',tf.matmul(tensor_x,tensor_y))

Using matmul:  tf.Tensor(
[[51 60]
 [ 9 18]], shape=(2, 2), dtype=int64)


In [20]:
print('Using addition: ',tf.add(tensor_x,tensor_y))

Using addition:  tf.Tensor(
[[12 12]
 [ 7  1]], shape=(2, 2), dtype=int64)


In [21]:
print('Using subtraction: ',tf.subtract(tensor_x,tensor_y))

Using subtraction:  tf.Tensor(
[[ 6  0]
 [-1 -1]], shape=(2, 2), dtype=int64)


In [22]:
print('Using division: ',tf.divide(tensor_x,tensor_y))

Using division:  tf.Tensor(
[[3.   1.  ]
 [0.75 0.  ]], shape=(2, 2), dtype=float64)


In [23]:
!pip install tensorflow==2.0.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [24]:
import tensorflow.compat.v1 as tf

In [26]:
tf.compat.v1.disable_eager_execution()

In [27]:
import tensorflow as tf
import numpy as np

def build_graph(max_count):
	init = np.zeros([max_count], dtype=np.int64); init[1] = 1
	series = tf.Variable(init)
	idx = tf.compat.v1.placeholder(dtype=tf.int32, shape=None)
	first_last = series[idx-1]
	second_last = series[idx-2]
	new_val = tf.add(first_last, second_last)
	step = series[idx].assign( new_val)
	return idx, step, series

def build_series(sess, max_count):
	idx, step, series = build_graph(max_count)
	sess.run(tf.compat.v1.global_variables_initializer())
	for i in range(2, max_count): 
		sess.run(step, {idx: i})
	return sess.run(series)

if __name__ == '__main__':
	sess = tf.compat.v1.InteractiveSession()
	print(build_series(sess, 10))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


[ 0  1  1  2  3  5  8 13 21 34]


In [28]:
import tensorflow as tf

factorial = tf.Variable(1, "factorial")
recursion = tf.Variable(1, "recursion")

# calculate factorial
mult = tf.multiply(recursion, factorial)
assign_fact = factorial.assign(mult)

init = tf.compat.v1.global_variables_initializer()

with tf.compat.v1.Session() as sess:
    sess.run(init) 
    for i in range(2,10):
        counter = recursion.assign(tf.constant(i))
        sess.run(counter)
        sess.run(assign_fact)

        print(i,"factorial is", sess.run(factorial))

    sess.close()

2 factorial is 2
3 factorial is 6
4 factorial is 24
5 factorial is 120
6 factorial is 720
7 factorial is 5040
8 factorial is 40320
9 factorial is 362880
